name = "frise-chezmehdi-net"
compatibility_date = "2024-01-01"

# Cloudflare Pages configuration
pages_build_output_dir = "dist"

[env.production]
name = "frise-chezmehdi-net"
[env.production.vars]
NODE_ENV = "production"

[env.preview]
name = "frise-chezmehdi-net-preview"
[env.preview.vars]
NODE_ENV = "development"